### ISSUE TITLE
建议上pip

### ISSUE THREAD

**Issue by leviathan0992** [cshuaimin/aget#1]

**Comment by cshuaimin** [comment]
这个我也想过，但目前有两个问题：
1. pypi 上已经有个叫做 aget 的优秀项目了，我这个得考虑改个名字；
2. 要想吸引更多的人用，就得有自己的独特优势，增加各种下载协议——目前只支持 HTTP/HTTPS 协议 :joy:

**Comment by cshuaimin** [comment]
@Leviathan1995 已添加到 pip，名字改为 aiodl 。
https://pypi.python.org/pypi/aiodl

**Comment by leviathan0992** [comment]
good!
