### ISSUE TITLE
安装了没有aiodl命令

### ISSUE THREAD

**Issue by coolicer** [cshuaimin/aget#2]
![image](https://user-images.githubusercontent.com/811078/37758753-46a38bd6-2dec-11e8-9e2b-25acf45b64d7.png)

**Comment by cshuaimin** [comment]
这个命令是由 setuptools 自动生成的，你先检查下你的 PATH 对不对，实在不行直接使用 `python3 -m aiodl` 也行。

**Comment by coolicer** [comment]
~ python3 -m aiodl
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'aiodl.__main__' found in sys.modules after import of package 'aiodl', but prior to execution of 'aiodl.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
usage: __main__.py [-h] [--output OUTPUT] [--fake-user-agent] [--num-tasks N]
                   [--max-tries N]
                   URL
__main__.py: error: the following arguments are required: URL

**Comment by cshuaimin** [comment]
OK. 0c3d17b469e5a5d85bd40009f70a28f5f3c9a034

**Comment by coolicer** [comment]
@cshuaimin 我的py3是用brew安装的，可以吗？

**Comment by cshuaimin** [comment]
当然可以了，只要是 3.5 或者以上版本，如果有报错，贴出来看看吧。

--------------原始邮件--------------
发件人："E.E.P "<notifications@github.com>;
发送时间：2018年3月28日(星期三) 晚上6:02
收件人："cshuaimin/aiodl" <aiodl@noreply.github.com>;
抄送："Chen Shuaimin "<i@tulip.ink>;"Mention "<mention@noreply.github.com>;
主题：Re: [cshuaimin/aiodl] 安装了没有aiodl命令 (#2)
-----------------------------------

@cshuaimin 我的py3是用brew安装的，可以吗？

**Comment by coolicer** [comment]
还是跟第一个图一样

**Comment by cshuaimin** [comment]
抱歉啊，我这没有 mac 的测试环境，但你前边不是可以用 `python3 -m aiodl` 运行了吗？

**Comment by coolicer** [comment]
不行，`python3 -m aiodl` 就报3楼的错，我要更新？

**Comment by cshuaimin** [comment]
3 楼有两个错，一个是 RuntimeWarning，我在 0c3d17b469e5a5d85bd40009f70a28f5f3c9a034 中修了，第二个是因为你没有提供下载的 URL 。。。
如果是第一个错，更新一下 `pip3 install --upgrade aiodl`

**Comment by coolicer** [comment]
好的，装完就有了。还要加上sudo哦
现在还可以用这个下载百度云吗？

**Comment by cshuaimin** [comment]
不行。百度云最近不带 cookie 好像不行了。有时间我把这个功能加上。

--------------原始邮件--------------
发件人："E.E.P "<notifications@github.com>;
发送时间：2018年3月28日(星期三) 晚上10:18
收件人："cshuaimin/aiodl" <aiodl@noreply.github.com>;
抄送："Chen Shuaimin "<i@tulip.ink>;"Manual "<manual@noreply.github.com>;
主题：Re: [cshuaimin/aiodl] 安装了没有aiodl命令 (#2)
-----------------------------------

好的，装完就有了。还要加上sudo哦
 现在还可以用这个下载百度云吗？

**Comment by coolicer** [comment]
那就是带上cookie还是可以用咯

**Comment by cshuaimin** [comment]
没错。

--------------原始邮件--------------
发件人："E.E.P "<notifications@github.com>;
发送时间：2018年3月28日(星期三) 晚上10:31
收件人："cshuaimin/aiodl" <aiodl@noreply.github.com>;
抄送："Chen Shuaimin "<i@tulip.ink>;"Manual "<manual@noreply.github.com>;
主题：Re: [cshuaimin/aiodl] 安装了没有aiodl命令 (#2)
-----------------------------------

那就是带上cookie还是可以用咯

**Comment by coolicer** [comment]
谢谢

**Comment by cshuaimin** [comment]
嗯，感谢支持。
